# Generated by Django 5.0.1 on 2024-02-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default=None, max_length=255)),
                ('age', models.CharField(default=None, max_length=255, null=True)),
                ('phone', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
