# Generated by Django 5.0.1 on 2024-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
