# Generated by Django 5.0.1 on 2024-02-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_password_alter_user_age_alter_user_phone'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventusermodel',
            name='event',
            field=models.ManyToManyField(to='event.eventmodel'),
        ),
        migrations.RemoveField(
            model_name='eventusermodel',
            name='event_picker',
        ),
        migrations.AddField(
            model_name='eventusermodel',
            name='event_picker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
