# Generated by Django 5.0.1 on 2024-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventmodel_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
