# Generated by Django 5.0.1 on 2024-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventmodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
    ]
