# Generated by Django 5.0.1 on 2024-02-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_eventmodel_created_at_eventmodel_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='expired_at',
            field=models.DateField(null=True),
        ),
    ]
