# Generated by Django 5.0.1 on 2024-02-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_eventmodel_expired_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventusermodel',
            old_name='event',
            new_name='events',
        ),
    ]
